main: de.christianschliz.spigotms.plugin.SpigotMS
name: SpigotMS
version: 0.4.0
author: DevTK

commands:
  microservices:
    description: Manage your active SpigotServices
    usage: /microservice [list|enable|disable|reload] [<service-name>]
    aliases:
      - ms
      - service
      - microservice